config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :number_of_guests, :price_per_night, :picture_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :destroy, :update]
  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?","%#{params[:query]}%")
      redirect_to flats_path
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @flats = Flat.all
    end
  end

  def show; end

  def edit
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?","%#{params[:query]}%")
      render :index
    end
  end

  def new
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?","%#{params[:query]}%")
      render :index
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @flat = Flat.new
    end
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :picture_url %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', flats_path, class: 'btn btn-danger ml-2' %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit flat</h1>

<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="cards">
  <% @flats.each do |flat| %>
    <div class="row">
      <div class="card">
        <div class="flat-card-image" style="background-image: url('<%= flat.picture_url %>')"></div>
        <div class="info">
          <h4><%= flat.name %></h4>
          <p><%= flat.address %></p>
          <p>
            <i class="fas fa-user-friends"></i><strong><%= flat.number_of_guests %>
            &nbsp;&nbsp;
            </strong> <strong><i class="fas fa-euro-sign"></i><%= flat.price_per_night %></strong>
          </p>
        </div>
        <div class="action">
          <p>
            <%= link_to "More info", flat_path(flat) %>
            <%= link_to "Edit", edit_flat_path(flat), class: 'ml-3 text-warning' %>
            <span class='ml-3 text-danger'>
              <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure you want delete #{flat.name}?"}, class: 'ml-3 text-danger' %>
            </span>
            </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1> Create new flat </h1>

<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>